language: python

python:
  - 3.7

os: windows

services: postgresql

env:
  - DJANGO=2.1.7

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py syncdb --noinput
